# Generated by Django 3.2.12 on 2022-02-19 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Warehouse name"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "store_warehouse",
            },
        ),
        migrations.CreateModel(
            name="StoreOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=256, verbose_name="Order number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ACCEPTED", "Accepted"),
                            ("SEND", "Send"),
                            ("IN_DELIVERY", "In delivery"),
                            ("ACCEPTED", "Stored"),
                        ],
                        default="NEW",
                        max_length=25,
                    ),
                ),
                (
                    "warehouse_order_id",
                    models.IntegerField(verbose_name="Warehouse order ID"),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="orders",
                        to="store.warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "store_order",
            },
        ),
    ]
