# Generated by Django 3.2.12 on 2022-02-20 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeorder",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders",
                to="store.warehouse",
                verbose_name="Warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="storeorder",
            name="warehouse_order_id",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Warehouse order ID"
            ),
        ),
    ]
