# Generated by Django 3.2.12 on 2022-02-19 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Warehouse name"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "db_table": "warehouse",
            },
        ),
        migrations.CreateModel(
            name="WarehouseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Order ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("ACCEPTED", "Accepted"),
                            ("SEND", "Send"),
                            ("IN_DELIVERY", "In delivery"),
                            ("ACCEPTED", "Stored"),
                        ],
                        default="NEW",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                ("store_order_id", models.IntegerField(verbose_name="Store order ID")),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="warehouse.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "db_table": "warehouse_order",
            },
        ),
    ]
