# Generated by Django 3.2.12 on 2022-02-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warehouseorder",
            name="order",
        ),
        migrations.AddField(
            model_name="warehouseorder",
            name="number",
            field=models.CharField(
                default=123, max_length=256, verbose_name="Order number"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="warehouseorder",
            name="store_order_id",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Store order ID"
            ),
        ),
    ]
